# Site settings
email: gabriel.henrique.a(@)gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: 

# SEO settings
title: Gabriel Adamante
description: 
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Gabriel Adamante
profile_img: 
profile: 
social:
  github: 

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:title/

#amp
ampdir: amp

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer, amp-jekyll]