# Site settings
email: gabriel.henrique.a(@)gmail.com 
baseurl: ""
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-92197570-1

# SEO settings
title: Gabriel Adamante
description: Artigos, Contos e Anotações
url: ""
twitter_username: 
default_img: 

# Profile settings
name: Gabriel Adamante
profile_img: autor.jpg
profile: Tocantinense nascido em Curitiba. Apaixonado por Literatura, Tecnologia e Hiking. Trabalhando com a Contabilizei para ajudar micro e pequenos empresários economizar e escapar da burocracia. 
social:
  github: http://github.com/g-adamante
  facebook: http://facebook.com/gabriel.adamante
  instagram: http://instagram.com/adamante
  linkedin: http://linkedin.com/in/g-adamante/

# Build settings
include: ["_categories"]
exclude: ["_screenshots", "Gemfile", "Gemfile.lock", "LICENSE.txt", "README.md"]
markdown: kramdown
permalink: /:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-paginate, jekyll-sitemap, octopress-autoprefixer]