---
title: Gabriel Adamante
timezone: UTC
remote_theme: chesterhow/tale
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: gabriel(@)adamante.com.br
baseurl: ''
paginate: 5
paginate_path: "/blog/page-:num"
google_analytics: UA-92197570-1
description: Artigos, Contos e Anotações
url: ''
twitter_username: 
default_img: 
name: Gabriel Adamante
profile_img: https://g-adamante.github.io/autor.jpg
profile: Tocantinense nascido em Curitiba e morando na Europa. Apaixonado por Literatura, Tecnologia e
  por caminhar.
social:
  github: http://github.com/g-adamante
  facebook: http://facebook.com/gabriel.adamante
  instagram: http://instagram.com/adamante
  linkedin: http://linkedin.com/in/g-adamante/
include:
- _categories
exclude:
- _screenshots
- Gemfile
- Gemfile.lock
- LICENSE.txt
- README.md
markdown: kramdown
permalink: "/:title/"
sass:
  style: compressed
gems:
- jekyll-sitemap
- jekyll-paginate
- octopress-autoprefixer
- jekyll-remote-theme
